# Language code specification: https://www.w3.org/International/articles/language-tags/
# Exclusion:
# - EN
# - SC -> TC
# - Regional
# - CJK Regional
# - Glyphs
# - Symbols
# - Numbers
# - Pure Katakana and Hiragana
# - Others
dataset:
  path: ./dataset/fonts
  exclusion:
    - ./Arphic（文鼎）/简体/文鼎习字体.TTF
    - ./Arphic（文鼎）/简体/文鼎大标宋简.TTF
    - ./Arphic（文鼎）/简体/文鼎小标宋简.TTF
    - ./Arphic（文鼎）/简体/文鼎报宋简.TTF
    - ./Arphic（文鼎）/简体/文鼎新艺体简.TTF
    - ./Arphic（文鼎）/简体/文鼎特圆简.TTF
    - ./Arphic（文鼎）/简体/文鼎特粗圆简.TTF
    - ./Arphic（文鼎）/简体/文鼎特粗宋简.TTF
    - ./Arphic（文鼎）/简体/文鼎特粗黑简.TTF
    - ./Arphic（文鼎）/简体/文鼎粗圆简.TTF
    - ./Arphic（文鼎）/简体/文鼎粗行楷简.TTF
    - ./Arphic（文鼎）/简体/文鼎粗钢笔行楷.ttf
    - ./Arphic（文鼎）/简体/文鼎粗魏碑简.TTF
    - ./Arphic（文鼎）/简体/文鼎行楷碑体.TTF
    - ./Arphic（文鼎）/简体/文鼎谁的字体.TTF
    - ./Arphic（文鼎）/简体/文鼎霹雳体.TTF
    - ./Arphic（文鼎）/简体/文鼎齿轮体.TTF
    - ./Arphic（文鼎）/繁体/文鼎POP-4.ttf
    - ./Arphic（文鼎）/繁体/文鼎中特廣告體.ttf
    - ./Arphic（文鼎）/繁体/文鼎中粗隸.ttf
    - ./Arphic（文鼎）/繁体/文鼎中行書.ttf
    - ./Arphic（文鼎）/繁体/文鼎中鋼筆行楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎中隸.ttf
    - ./Arphic（文鼎）/繁体/文鼎勘亭流.ttf
    - ./Arphic（文鼎）/繁体/文鼎古印體繁.TTF
    - ./Arphic（文鼎）/繁体/文鼎圓立體.ttf
    - ./Arphic（文鼎）/繁体/文鼎妞妞體.ttf
    - ./Arphic（文鼎）/繁体/文鼎新中特黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎新中黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎新中黑外字一.ttf
    - ./Arphic（文鼎）/繁体/文鼎新特黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎新粗黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎新細黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎新藝體.ttf
    - ./Arphic（文鼎）/繁体/文鼎海報體.ttf
    - ./Arphic（文鼎）/繁体/文鼎瀟灑體.ttf
    - ./Arphic（文鼎）/繁体/文鼎火柴體.ttf
    - ./Arphic（文鼎）/繁体/文鼎特黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗明.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗行楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗鋼筆行楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗隸.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗魏碑.ttf
    - ./Arphic（文鼎）/繁体/文鼎粗黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎細楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎細鋼筆行楷.ttf
    - ./Arphic（文鼎）/繁体/文鼎細黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎荊棘體.ttf
    - ./Arphic（文鼎）/繁体/文鼎行楷碑體.ttf
    - ./Arphic（文鼎）/繁体/文鼎誰的字體.ttf
    - ./Arphic（文鼎）/繁体/文鼎賤狗體.ttf
    - ./Arphic（文鼎）/繁体/文鼎超圓.ttf
    - ./Arphic（文鼎）/繁体/文鼎超黑.ttf
    - ./Arphic（文鼎）/繁体/文鼎雕刻體.ttf
    - ./Arphic（文鼎）/繁体/文鼎霹靂體.ttf
    - ./Arphic（文鼎）/繁体/文鼎顏楷九宮體.ttf
    - ./Arphic（文鼎）/繁体/文鼎ＰＯＰ－２.TTF
    - ./Founder Type（方正）/韩文/方正朝文中圆.TTF
    - ./Founder Type（方正）/简繁/ttf/方正宋体S-超大字符集(SIP).TTF
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_503L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 503L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_504L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 504L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 505L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_506L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 506L.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_508R.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 508R.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_509R.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 509R.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_510M.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 510M.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_511M.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 511M.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_512B.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 512B.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_513B.ttf
    - ./Founder Type（方正）/简繁/ttf/方正悠黑_GBK 513B.ttf
    - ./其他/日文/CRＣ＆Ｇ半古印 - CRPＣ＆Ｇ半古印.TTC
    - ./其他/日文/FGＣ＆Ｇ半古印 - FGPＣ＆Ｇ半古印.TTC
    - ./其他/日文/FGCCHGW3.TTC
    - ./其他/日文/Jiyukobo（字游工房）/假名/築地体一号太仮名.otf
    - ./其他/日文/Jiyukobo（字游工房）/假名/築地体三十五ポイント仮名.otf
    - ./其他/日文/Jiyukobo（字游工房）/假名/築地体三号太仮名.otf
    - ./其他/日文/TypeBank/假名/RoVenetian-Book.otf
    - ./其他/日文/RICOH（理光）/HGAkaneHeiseiMarugoW8.ttf
    - ./其他/日文/RICOH（理光）/HGHeiseiMinchotaiW9 - HGPHeiseiMinchotaiW9 - HGSHeiseiMinchotaiW9.ttc
    - ./其他/日文/恋文ペン字.TTF
    - ./其他/简体/汉鼎简新艺体.TTF
  specs:
    - path:
        - ./Adobe/CJK
      rule: |
        lambda x: \
          x.split('/')[-1].split('\\')[-1].startswith('SourceHanSans-') \
          or x.split('/')[-1].split('\\')[-1].startswith('SourceHanSerif-')
      language: CJK
    - path:
        - ./Google（谷歌）/CJK
      rule: |
        lambda x: \
          x.split('/')[-1].split('\\')[-1].startswith('NotoSansCJK-') \
          or x.split('/')[-1].split('\\')[-1].startswith('NotoSansMonoCJK-') \
          or x.split('/')[-1].split('\\')[-1].startswith('NotoSerifCJK-')
      language: CJK
    - path:
        - ./Arphic（文鼎）/简体
        - ./DynaFont（华康）/简体
        - ./Fontworks/简体
        - ./Founder Type（方正）/简体
        - ./Hanyi Fonts（汉仪）/简体
        - ./Microsoft（微软）/简体
        - ./Monotype（蒙纳）/简体
        - ./SinoType（华文）/简体
        - ./TensenType（腾祥）/简体
        - ./其他/简体
      language: zh-Hans
    - path:
        - ./Adobe/繁体
        - ./Arphic（文鼎）/繁体
        - ./Fontworks/繁体
        - ./Founder Type（方正）/繁体
        - ./Hanyi Fonts（汉仪）/繁体
        - ./Microsoft（微软）/繁体
        - ./Monotype（蒙纳）/繁体
        - ./SinoType（华文）/繁体
        - ./TensenType（腾祥）/繁体
        - ./其他/繁体
      language: zh-Hant
    - path:
        - ./Adobe/简繁
        - ./Arphic（文鼎）/简繁
        - ./DynaFont（华康）/简繁
        - ./Founder Type（方正）/简繁
        - ./Hanyi Fonts（汉仪）/简繁
        - ./Microsoft（微软）/简繁
        - ./Monotype（蒙纳）/简繁
        - ./Morisawa（森泽）/简繁
        - ./SinoType（华文）/简繁
        - ./TensenType（腾祥）/简繁
        - ./其他/简繁
      language: zh
    - path:
        - ./Adobe/日文
        - ./Arphic（文鼎）/日文
        - ./DynaFont（华康）/日文
        - ./Fontworks/日文
        - ./Monotype（蒙纳）/日文
        - ./Morisawa（森泽）/日文/MorisawaAOTF/日文
        - ./Morisawa（森泽）/日文/MorisawaAPOTF
        - ./Morisawa（森泽）/日文/MorisawaGOTF
        - ./Morisawa（森泽）/日文/MorisawaUOTF
        - ./TensenType（腾祥）/日文
        - ./其他/日文
      language: ja
    - path:
        - ./DynaFont（华康）/繁体/港版
      language: zh-Hant-HK
    - path:
        - ./DynaFont（华康）/繁体/台版
      language: zh-Hant-TW
    - path:
        - ./DynaFont（华康）/韩文
        - ./Fontworks/韩文
        - ./Founder Type（方正）/韩文
        - ./Morisawa（森泽）/韩文
        - ./其他/韩文
      language: ko
